Release 3.1.0
yandexmobile/yandex-ads-sdk-android pull request #83
Opened 2020-10-19 11:03 UTC by mobile-ads-github

2020-10-19 11:04 UTC, dmitryfisko approved these changes

2020-10-20 01:50 UTC, satsakul requested changes
Необходимо подробнее описать changelog 3.1.0

2020-10-20 09:34 UTC, mobile-ads-github commented
> Необходимо подробнее описать changelog 3.1.0

Fixed

2020-10-20 11:40 UTC, satsakul approved these changes

2020-10-20 11:46 UTC, merged